### ISSUE TITLE
Add support for reStructuredText (RST)

### ISSUE THREAD

**Issue by joschi** [redpen-cc/redpen-intellij-plugin#14]
IntelliJ IDEA supports [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText) markup via https://plugins.jetbrains.com/plugin/7124 (shipped by default). reStructuredText is for example being used by the [Sphinx documentation generator](http://www.sphinx-doc.org/) (which is supported by https://readthedocs.org/).

It would be awesome if the RedPen IntelliJ IDEA plugin also supported this.

Refs redpen-cc/redpen#23

**Comment by takahi-i** [comment]
Thank you very much for making this issue @joschi! We will support reStructuredText. The cost for supporting the format is not so high. Hopefully we can make it this summer.

**Comment by takahi-i** [comment]
Hi @joschi,  I am very sorry the make you wait for long time.  Finished the implementation of reST parser in RedPen core last week. After the release of RedPen this  month, I will add the support reStructureText immediately.

**Comment by joschi** [comment]
@takahi-i No problem and thank you very much for implementing this feature! ❤️

**Comment by takahi-i** [comment]
Hi @joschi, I released the new RedPen IntelliJ plugin yesterday. 

https://plugins.jetbrains.com/plugin/8210-redpen-plugin

This version supports reStructuredTextFormat.

![screen shot 2017-06-07 at 0 20 15](https://user-images.githubusercontent.com/339436/26857653-10b27bc6-4b67-11e7-8539-a28b0c2d69f9.png)
